const $=s=>document.querySelector(s), views=["bios","boot","chooser","os"];let state={system:"windows",booting:false,bootTimer:null,osReady:false};
const systems={
 windows:{name:"Windows 11",icon:"▦",cls:"win",color:"#087dea"},
 mac:{name:"macOS",icon:"",cls:"mac"},
 ubuntu:{name:"Ubuntu Linux",icon:"●",cls:"linux"},
 arch:{name:"Arch Linux",icon:"△",cls:"arch"},
 steam:{name:"SteamOS",icon:"🎮",cls:"steam"}
};
function show(name){views.forEach(v=>$(`#${v}`).classList.toggle("hidden",v!==name))}
function renderChooser(){show("chooser");$("#chooser").innerHTML=`<div class="chooser-box"><h1>🖥️ VIRTUAL PC</h1><p style="text-align:center;color:#9aa7ba">Выбери операционную систему для виртуального компьютера</p><div class="systems">${Object.entries(systems).map(([id,s])=>`<div class="system" data-os="${id}"><div class="logo">${s.icon}</div><b>${s.name}</b><br><small>Запустить</small></div>`).join("")}</div><div class="chooser-tip">ESC во время загрузки → BIOS • R → перезагрузка</div></div>`;
document.querySelectorAll("[data-os]").forEach(e=>e.onclick=()=>boot(e.dataset.os))}
function boot(id=state.system){state.system=id;state.booting=true;show("boot");let s=systems[id];$("#boot").innerHTML=`<div class="bootbox"><div class="boot-title">${s.icon} ${s.name} Boot</div><div class="bar"><i id="bootbar"></i></div><div class="bootline" id="bootline">Initializing virtual hardware...</div></div>`;let p=0;clearInterval(state.bootTimer);state.bootTimer=setInterval(()=>{p+=Math.random()*16+7;$("#bootbar").style.width=Math.min(100,p)+"%";$("#bootline").textContent=p<35?"Checking virtual hardware...":p<70?"Loading kernel and drivers...":p<95?"Starting desktop services...":"Starting user interface...";if(p>=100){clearInterval(state.bootTimer);state.booting=false;openOS(id)}},160)}
function openOS(id){show("os");let s=systems[id];$("#os").innerHTML=`<div class="desktop ${s.cls}"><div class="taskbar"><button class="taskbtn" id="menuBtn">☰</button><b>${s.name}</b><span style="margin-left:auto">🔊  ▣  ${new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</span></div><div class="window" id="mainWindow"><div class="winbar"><b id="windowTitle">Desktop</b><span>— □ ×</span></div><div class="winbody" id="windowBody"><h2>Добро пожаловать 👋</h2><p>Это виртуальная ${s.name}. Нажимай приложения на панели.</p><div class="app-grid"><div class="app">📁 Файлы</div><div class="app">🌐 Браузер</div><div class="app">⚙️ Настройки</div></div></div></div><div id="menu"></div></div>`;
$("#menuBtn").onclick=()=>toggleMenu(id)}
function toggleMenu(id){let m=$("#menu");if(m.innerHTML){m.innerHTML="";return}let s=systems[id];m.innerHTML=`<div class="start"><b>${s.name}</b><button onclick="openApp('browser')">🌐 Браузер</button><button onclick="openApp('files')">📁 Файлы</button><button onclick="openApp('terminal')">⌨ Терминал</button><button onclick="restart()">🔄 Перезагрузить</button><button onclick="renderChooser()">↪ Выбрать другую ОС</button></div>`}
function openApp(app){$("#menu").innerHTML="";let title="",body="";if(app==="browser"){title="Browser";body="<h2>🌐 Веб-браузер</h2><p>Адрес</p><input id='fakeUrl' value='https://example.com' style='width:100%;padding:12px'><p class='small'>Это безопасная демонстрация интерфейса браузера внутри виртуальной ОС.</p>"}else if(app==="files"){title="File Manager";body="<h2>📁 Файлы</h2><div class='app-grid'><div class='app'>📄 Documents</div><div class='app'>🖼️ Pictures</div><div class='app'>🎵 Music</div><div class='app'>📦 Downloads</div></div>"}else{title="Terminal";body=`<h2>⌨ Терминал</h2><div class="terminal">user@virtual-pc:~$ neofetch\nOS: ${systems[state.system].name}\nKernel: VirtualKernel 1.0\nShell: vsh\n\nuser@virtual-pc:~$ _</div>`}$("#windowTitle").textContent=title;$("#windowBody").innerHTML=body}
function restart(){show("boot");boot(state.system)}
window.addEventListener("keydown",e=>{if((e.key==="Escape"||e.key==="F2")&&state.booting){clearInterval(state.bootTimer);state.booting=false;renderBIOS()}if(e.key.toLowerCase()==="r"&&!state.booting&&!$("#os").classList.contains("hidden"))restart()});
function renderBIOS(){show("bios");let selected=0,items=["Boot Manager","System Information","Virtual Hardware","Date & Time","Save & Exit"];$("#bios").innerHTML=`<div class="bios"><h1>VIRTUAL PC UEFI BIOS</h1><p>Firmware 1.0.0 • Virtual motherboard • ${navigator.platform}</p>${items.map((x,i)=>`<div class="row ${i===0?"selected":""}" data-bi="${i}"><b>${x}</b><span>→</span></div>`).join("")}<div class="footer">↑↓ Select &nbsp; Enter Select &nbsp; ESC Exit BIOS &nbsp; F10 Save & Exit</div></div>`;let rows=[...document.querySelectorAll("[data-bi]")];rows.forEach((r,i)=>r.onclick=()=>biosAction(i));function biosAction(i){if(i===0){renderChooser()}else if(i===1){alert("Virtual PC\\nCPU: Virtual 8-Core\\nRAM: 16 GB\\nDisk: 256 GB\\nFirmware: UEFI 1.0")}else if(i===2){alert("Virtual Hardware\\nDisplay: 1920×1080\\nNetwork: Virtual Ethernet\\nAudio: Virtual HD Audio")}else if(i===3){alert("Date & Time\\n"+new Date().toString())}else renderChooser()}}
renderChooser();